/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author firlisaanggraeni
 */
public class Menu_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Menu_GUI
     */
    public Menu_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new javax.swing.JPanel();
        background2 = new javax.swing.JPanel();
        background3 = new javax.swing.JPanel();
        btnlogin2 = new javax.swing.JButton();
        btnfaq = new javax.swing.JButton();
        btnabout = new javax.swing.JButton();
        btninstruction = new javax.swing.JButton();
        btncredits = new javax.swing.JButton();
        btndaftarscore = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background1.setBackground(new java.awt.Color(0, 153, 153));

        background2.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout background2Layout = new javax.swing.GroupLayout(background2);
        background2.setLayout(background2Layout);
        background2Layout.setHorizontalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        background2Layout.setVerticalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        background3.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout background3Layout = new javax.swing.GroupLayout(background3);
        background3.setLayout(background3Layout);
        background3Layout.setHorizontalGroup(
            background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        background3Layout.setVerticalGroup(
            background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnlogin2.setFont(new java.awt.Font("Silom", 1, 12)); // NOI18N
        btnlogin2.setForeground(new java.awt.Color(0, 153, 153));
        btnlogin2.setText("Log in");

        btnfaq.setFont(new java.awt.Font("Silom", 1, 12)); // NOI18N
        btnfaq.setForeground(new java.awt.Color(0, 153, 153));
        btnfaq.setText("FAQ");

        btnabout.setFont(new java.awt.Font("Silom", 1, 12)); // NOI18N
        btnabout.setForeground(new java.awt.Color(0, 153, 153));
        btnabout.setText("About");

        btninstruction.setFont(new java.awt.Font("Silom", 1, 12)); // NOI18N
        btninstruction.setForeground(new java.awt.Color(0, 153, 153));
        btninstruction.setText("Instruction");
        btninstruction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninstructionActionPerformed(evt);
            }
        });

        btncredits.setFont(new java.awt.Font("Silom", 1, 12)); // NOI18N
        btncredits.setForeground(new java.awt.Color(0, 153, 153));
        btncredits.setText("Credits");
        btncredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreditsActionPerformed(evt);
            }
        });

        btndaftarscore.setFont(new java.awt.Font("Silom", 1, 12)); // NOI18N
        btndaftarscore.setForeground(new java.awt.Color(0, 153, 153));
        btndaftarscore.setText("Daftar Score");

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(background2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(background3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(background1Layout.createSequentialGroup()
                                .addComponent(btninstruction, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                .addComponent(btncredits, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(background1Layout.createSequentialGroup()
                                .addComponent(btnfaq, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnabout, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btndaftarscore, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnlogin2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(background3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btninstruction, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncredits, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnlogin2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndaftarscore, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnfaq, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnabout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreditsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncreditsActionPerformed

    private void btninstructionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninstructionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btninstructionActionPerformed

    /**
     * @param args the command line arguments
     */

    public JButton getBtnabout() {
        return btnabout;
    }

    public void setBtnabout(JButton btnabout) {
        this.btnabout = btnabout;
    }

    public JButton getBtncredits() {
        return btncredits;
    }

    public void setBtncredits(JButton btncredit) {
        this.btncredits = btncredit;
    }

    public JButton getBtnfaq() {
        return btnfaq;
    }

    public void setBtnfaq(JButton btnfaq) {
        this.btnfaq = btnfaq;
    }

    public JButton getBtninstruction() {
        return btninstruction;
    }

    public void setBtninstruction(JButton btninstruction) {
        this.btninstruction = btninstruction;
    }

    public JButton getBtnlogin2() {
        return btnlogin2;
    }

    public void setBtnlogin2(JButton btnlogin2) {
        this.btnlogin2 = btnlogin2;
    }

    public JButton getBtndaftarscore() {
        return btndaftarscore;
    }

    public void setBtndaftarscore(JButton btndaftarscore) {
        this.btndaftarscore = btndaftarscore;
    }
    
    public void AddActionListener(ActionListener a){
        btnlogin2.addActionListener(a);
        btninstruction.addActionListener(a);
        btncredits.addActionListener(a);
        btnfaq.addActionListener(a);
        btnabout.addActionListener(a);
        btndaftarscore.addActionListener(a);
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background1;
    private javax.swing.JPanel background2;
    private javax.swing.JPanel background3;
    private javax.swing.JButton btnabout;
    private javax.swing.JButton btncredits;
    private javax.swing.JButton btndaftarscore;
    private javax.swing.JButton btnfaq;
    private javax.swing.JButton btninstruction;
    private javax.swing.JButton btnlogin2;
    // End of variables declaration//GEN-END:variables
    
}
